### ISSUE TITLE
D language is not reported

### ISSUE THREAD

**Issue by JohanEngelen** [madnight/githut#104]
I do not see the D language in the data. Do you know what is causing that?  (Github does recognize that language, as you can see e.g. here: https://github.com/dlang/dmd)

**Comment by madnight** [comment]
I think the D language simply does not rank among the top 50 languages. Here is a list of languages that I have filtered out because they are not considered programming languages. 

https://github.com/madnight/githut/blob/master/src/common/NoLanguages.js

As you can see, D is not in the filter. Therefore, the only other explanation I can offer is that it probably falls somewhere within the top 50 - 100 languages and hence, is not listed on Githut.

**Comment by JohanEngelen** [comment]
I looked at the data json files, and there I do see "D":
https://github.com/madnight/githut/blob/e7091f06565df0bfbe34dace9d0a592875397ff4/src/data/gh-pull-request.json#L6933

**Comment by madnight** [comment]
@JohanEngelen Yes, it is in the data, which strongly suggests that it hovers in the 50 - 100 range, as I believe I set LIMIT 100 somewhere in my SQL query. However, it is not among the top 50 programming languages on GitHub. In principle, you could verify this yourself by running some queries on the public BigQuery dataset from GitHub. For comparison, other rankings such as https://pypl.github.io/PYPL.html also don't list D.

I assume you are a D programmer and would like to see it in the ranking. I'm sorry that it is not more popular at the moment, but this could change in the future.
