### ISSUE TITLE
Languages in graph not synced with table data

### ISSUE THREAD

**Issue by kanaka** [madnight/githut#11]
The languages shown in the graph are not the same as the top 10 from the table. For example, on the Pull Requests graph, Go (6) and TypeScript (10) are not included in the graph whereas Scala (12) and Objective-C (16) are included in the 10 languages in the graph.

**Comment by madnight** [comment]
That is normal since that are two different time spans. This behaviour is described in the description text on the website.

**Comment by kanaka** [comment]
Do you mean that that graph shows languages that were the top ones in 2012Q2? Or is there some sort of averaging being across the full time frame? It's not clear from "calculated over a different time period" how it is calculated. The behavior I was expecting was that the languages shown in the graph would be the ones at the end of the time frame being displayed.

**Comment by madnight** [comment]
Yes, the graph shows the top 10 languages from 2012/Q2 - 2017/Q4 and the table always shows a single quarter e.g 2017/Q4. The problem is, if the graph would show the ranking for one month, then this could include languages such as TypeScript for which there is no (language didn't existed yet) or not enough data back in 2012.

**Comment by kanaka** [comment]
Okay, I think I'm a more clear now on how they are being chosen.

Proposal: scan across the time frame and select the top 10 languages from each quarter and merge them into the set of languages to graph (which will be a few more than 10 languages). New languages would start at bottom of the chart in the quarter in which they appear (which would almost certainly be prior to quarter when they entered the top 10). I think that would result in the least confusion about the graph. Alternatively, I think the languages in the graph should be the ones that are in the top 10 in the current quarter. I think that is probably what people are most interested when they look at the graph (at least, that's true for me). I don't think it's a problem for new languages to appear after the beginning of the graph. In fact, if a language that is new since 2012 has made it into the top 10, that's a really interesting data-point.

**Comment by madnight** [comment]
That sounds logical to me. I think i will go with "Alternatively, I think the languages in the graph should be the ones that are in the top 10 in the current quarter."

**Comment by madnight** [comment]
Okay should be correct now.

**Comment by madnight** [comment]
The top 10 languages in the graph should now always match the top 10 of the table.

**Comment by kanaka** [comment]
The languages in the graph however, when I select a different quarter it doesn't change the time range of the graph. Were you intending for the graph to update to reflect the year/quarter selected?

But even for the 2017-Q4 table, the numbers don't seem to quite match the graph. For example, for Pull Requests in 2017-Q4, Javascript shows as 22.290% in the table, but the rolling over the last data point in the JavaScript graph shows (25.84%). Likewise python is 15.823% in the table and 18.34% in the table. My guess as to what is happening is that the percentage for the table and graph are being calculated independently and that the graph percentage is only the percentage of the 10 languages shown. It would probably be better to use the same data for calculating both percentages (it took me a while to figure out why they didn't match).

BTW, I don't want to sound like I'm complaining. I appreciate the work that you are putting into this. I just want it to be as good as it can be :-)

**Comment by madnight** [comment]
> when I select a different quarter it doesn't change the time range of the graph

My intention is that the graph shows the history of the top 10 languages over the overall time period (since 2012). I'm not so much interested in calculating a graph for a quarter period, since daily fluctuations over a 90 day period are not so interesting in my opinion. The difference with the latest update is that the top 10 of the graph always now always match the top 10 of the current selected (Y/Q) table.

> My guess as to what is happening is that the percentage for the table and graph are being calculated independently

Thats true, but if i adjust the percentages to match the ranking table, then the graph would show percentage numbers that do not add up to 100% (since top 10 - 50 languages are not shown, but would be used for the percentage calculation). I'm not sure if this logic wouldn't be even more confusing.

> I don't want to sound like I'm complaining.

I appreciate every constructive feedback : )

BTW, noVNC is a very nice project!
